apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-shop-user-deployment
  labels:
    app: food-shop-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-shop-user
  template:
    metadata:
      labels:
        app: food-shop-user
    spec:
      containers:
      - name: food-shop-user
        image: 029225022811.dkr.ecr.ap-southeast-1.amazonaws.com/food_shop_user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"