apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-shop-user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-shop-user-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
